# Tomcat
server:
    tomcat:
        uri-encoding: UTF-8
        max-threads: 1000
        min-spare-threads: 30
    port: 8081
    context-path: /
spring:
    profiles:
        active: dev
    devtools:
        restart:
           exclude: static/**,public/**

storage:
    webPath: http://localhost
    imagePath: http://localhost
    
vod:
    appid: wxfed4cb908fedfd14
    secret: 50f5974e8e2f15eb86fccbe258efa959


