spring:
    datasource:
        url: jdbc:mysql://127.0.0.1/vod?useSSL=false
        username: root
        password: Feng123456
        driver-class-name: com.mysql.jdbc.Driver
    thymeleaf:
        cache: false